<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "{{%posts}}".
 *
 * @property int $id
 * @property string $title
 * @property string $body
 * @property int $image_id
 * @property string $date_created
 *
 * @property PostUser[] $postUsers
 * @property User[] $users
 */
class Posts extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return '{{%posts}}';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['title', 'body'], 'required'],
            [['title', 'body'], 'string'],
            [['image_id'], 'integer'],
            [['date_created'], 'safe'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'title' => 'Title',
            'body' => 'Body',
            'image_id' => 'Image ID',
            'date_created' => 'Date Created show data',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPostUsers()
    {
        return $this->hasMany(PostUser::className(), ['post_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUsers()
    {
        return $this->hasMany(User::className(), ['id' => 'user_id'])->viaTable('{{%post_user}}', ['post_id' => 'id']);
    }

    public function afterSave($insert, $changedAttributes)
    {
        //todo:: afterSave відповідає не тільки за інсерт але й за апдейт! При апдейті не потрібно створювати новий звязок
        $ps = new PostUser();
        $ps->post_id = $this->id;
        $ps->user_id = Yii::$app->user->getId();
        $ps->save();
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
    }
}
